[features]
seeds = false
skip-lint = false
[programs.devnet]
count = "H6v3DVHdLfu5GMrKtJKGgC1tBYBejP2U1wA8yNofRPcZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
